feat: set a max value for kafka token lifetime
gravitee-io/gravitee-policy-jwt pull request #133
Opened 2024-11-28 15:01 UTC by phiz71

**Issue**

https://gravitee.atlassian.net/browse/APIM-7143

**Description**

Set a max value for kafka token lifetime.
It's required to avoid kafka client re-authent storm

2024-11-28 16:16 UTC, jhaeyaert requested changes

2024-11-28 16:16 UTC, jhaeyaert commented on src/main/java/io/gravitee/policy/jwt/JWTPolicy.java
> +                                60 * 60 * 1000L
You can add a constant

2024-11-28 17:07 UTC, jhaeyaert approved these changes

2024-11-29 06:57 UTC, ytvnr approved these changes

2024-11-29 06:58 UTC, merged

2024-11-29 07:02 UTC, graviteeio commented
:tada: This PR is included in version 6.0.0-alpha.4 :tada:

The release is available on:
- `6.0.0-alpha.4`
- [GitHub release](https://github.com/gravitee-io/gravitee-policy-jwt/releases/tag/6.0.0-alpha.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-12-30 15:18 UTC, graviteeio commented
:tada: This PR is included in version 6.0.0 :tada:

The release is available on:
- `6.0.0`
- [GitHub release](https://github.com/gravitee-io/gravitee-policy-jwt/releases/tag/6.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: